### ISSUE TITLE
Index Allocation By Address in the Subsumption Table

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#101]
Currently, allocations in the subsumption table is indexed by base allocation (an LLVM value) first, and then its actual address. The keys of the table are stored in `SubsumptionTableEntry::concreteAddressStoreKeys` and `SubsumptionTableEntry::symbolicAddressStoreKeys`, which are vectors of `llvm::Value` pointers. However, it is possible that the same (concrete) address is actually referenced via different bases, making subsumption checks less reliable when indexed using the base, as we may fail to retrieve the correct memoed program state (the interpolant). Instead, the program state should be indexed using the addresses themselves to be correct.

**Comment by domainexpert** [comment]
I believe here we need an example.

**Comment by feliciahalim** [comment]
@domainexpert Is program equivalence example that does not have any subsumption like [grading-examples/count](https://github.com/tracer-x/grading-examples/blob/master/count.c)  could be used as an example?

**Comment by domainexpert** [comment]
@feliciahalim Does the example demonstrate the issue?

**Comment by feliciahalim** [comment]
@domainexpert not sure if the example could demonstrate the issue. Need to have further look into the issue.

**Comment by domainexpert** [comment]
@feliciahalim It's ok not to spend time on this. A simple example would be some C program that writes past a buffer and into a buffer of different allocation. I will look into this again sometimes.

**Comment by domainexpert** [comment]
Resolved via #284.
