### ISSUE TITLE
Missing error report

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#133]
KLEE reported two error reports in different locations. However, Tracer-x has reported only one report. It is caused by the error paths is subsumed by an empty interpolant. 

This is the `Heartbleed.c` code:
```
#include <stdlib.h>
#include <klee/klee.h>

char *SSL_get_shared_ciphers(const char *cp, char *buf, int len)
{
    char *p = buf;

    for (; *cp; )
    {
        if (len-- == 0)
        {
            *p='\0';
            return(buf);
        }
        else
            *(p++)= *(cp++);
    }
    *(p++)=':';

    p[-1]='\0';
    return(buf);
}

/* test function */

#define BUF_SIZE 10
#define MAX_S 20

int main()
{
    char *buf = malloc(BUF_SIZE);
    klee_make_symbolic(buf, BUF_SIZE, "buf");

    // Set up string variable 'name' with arbitrary content
    // and length at most MAX_S (including terminator).

    int s = MAX_S;
    char *name = malloc(s);
    name[s-1] = '\0';
    klee_make_symbolic(name, s, "name");


    // Check SSL_get_shared_ciphers for all strings 'name'
    // of size up to MAX_S.

    SSL_get_shared_ciphers(name, buf, BUF_SIZE);

    return 0;
}
```

**Comment by feliciahalim** [comment]
@domainexpert ` coreutils/paste` error reports is also missing. I run `coreutils/paste` and Tracer-x finished for 1 and half hour without error reports where KLEE has reported error reports.

**Comment by domainexpert** [comment]
@feliciahalim I think this is a bug: the loop condition `*cp`, that is, the KLEE constraint `0 == name[0]` should be in the interpolant.

**Comment by domainexpert** [comment]
@feliciahalim I revised my analysis: actually the value of the pointer p, which has never appeared in any conditional, should be included as in the core (interpolant). At Line 18 (the `*(p++)=':';` instruction), the fact that there is no memory error in the first visit should be equated to a proof (even without any solver call). It is as if we have a proof that "`p` is within the allocated memory", and therefore the value of `p` should be included in the unsatisfiability core of this "proof".

**Comment by domainexpert** [comment]
@feliciahalim Basically we should extract the unsatisfiability core and compute the interpolant at Line 3567 of `Executor.cpp`.

**Comment by feliciahalim** [comment]
@domainexpert Line 3567 in Executor.cpp is 
```
  bool incomplete = state.addressSpace.resolve(state, solver, address, rl,
                                               0, coreSolverTimeout);
```

Is it mean we need to modify resolve method?

**Comment by domainexpert** [comment]
@feliciahalim Maybe. I am looking into this.
