### ISSUE TITLE
Move Repository to A New Organization

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#16]
At some point we need to create a GitHub organization for this project and move our KLEE repository to be under that organization.

**Comment by domainexpert** [comment]
@feliciahalim @nguyenquocbinh I have created a new organization https://github.com/tracer-x/ and sent you invites. Please accept.

**Comment by feliciahalim** [comment]
@domainexpert  I have accepted the invitation. Thanks.

**Comment by domainexpert** [comment]
@feliciahalim I have made you an owner of tracer-x.

**Comment by nguyenquocbinh** [comment]
I accepted it too. Thank you.

**Comment by domainexpert** [comment]
@nguyenquocbinh @feliciahalim Awesome! Thanks, guys!

**Comment by domainexpert** [comment]
@nguyenquocbinh I've made you an owner too.

**Comment by domainexpert** [comment]
@feliciahalim @nguyenquocbinh If you want people to know that you proudly belong to the tracer-x organization, click on tracer-x icon on your GitHub profile page and select Membership: public. Then when others browse your profile page, the tracer-x icon will show for them as well.

**Comment by feliciahalim** [comment]
@domainexpert  I have made my membership public. Thank you.

**Comment by domainexpert** [comment]
@feliciahalim No obligation, but thank you for your help in promoting the project.
