### ISSUE TITLE
Simplify three options into one

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#252]
Three options `-special-function-bound-interpolation`, `-no-bound-check` and `-no-bound-interpolation` can be unified into a single option, perhaps still named `-special-function-bound-interpolation`, which performs bounds check and interpolation in the special function `tracerx_check`, but disables bounds check and interpolation outside of the function named `tracerx_check`. Not actually providing the special function means that we disable all bounds check and bounds interpolation throughout the program.

Note also that `-no-interpolation` should still disable all interpolation.

**Comment by rasoolmaghareh** [comment]
At the current stage, `-no-bound-check` disables bound check at every point or still it performs bound check at `tracerx_check`? From the implementation, I think `-no-bound-check` is disabling bound check at every point. We didn't exclude `tracerx_check` function at any point.

**Comment by domainexpert** [comment]
@rasoolmaghareh You are right that `-no-bound-check` disables all check even in `tracerx_check`. It is all currently confusing, so I would like to propose that we unify everything under `-special-function-bound-interpolation`.

**Comment by rasoolmaghareh** [comment]
Observation:

@domainexpert, I have noticed that the if the bound pointer is instantiated outside the main function, the generated interpolants are empty. Ex.

`char _bound[60];
char *wcet = _bound ;
int main(int argc, char **argv)
{  
  wcet ++;
  ...
  tracerx_check(wcet);
}`

In case there are more than one function in a benchmark, the bounds variable should be declared and initialized as follow:

`char _bound[60];
char *wcet;
int main(int argc, char **argv)
{  
  wcet = _bound ;
  ...
  wcet ++;
  ...
  tracerx_check(wcet);
}`

**Comment by domainexpert** [comment]
Resolved via #258.
