### ISSUE TITLE
Counter-example not generated from failed WCET bound-check 

### ISSUE THREAD

**Issue by rasoolmaghareh** [tracer-x/klee#255]
In any of the steps of the bound-check algorithm, in case the bound is safe the upper-bound is divided by two. In case the bound is not safe, the bound generated from the counter-example should be set is the new lower-bound. 

Currently the new lower-bound  is set from the previous lower-bound+1.

**Comment by domainexpert** [comment]
@rasoolmaghareh Is this about the current master branch?

**Comment by rasoolmaghareh** [comment]
This one can be resolved by adding the following tracerx_check function to a benchmark:
`void tracerx_check(char *p) { printf("Timing of Path:%d\n",(int)p-(int)(&(_bound))); *p;} `
