### ISSUE TITLE
Tracer-X slower than KLEE due to disabled pre-solving

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#28]
It is mainly caused by disabling the equality substitution (a pre-solving simplification).  When equality substitution is disabled, then, simplifyExpr(expr) will not be called. And therefore constraint solving will be slower. The reason for disabling the expression simplification is because it mangles the path condition, and we can therefore no longer identify the core. One of the example where it shows Tracer-X is slower than KLEE can be seen in here: https://github.com/feliciahalim/klee-examples/commit/15ee21671643aafb872523d9064c5502258a6bfd

**Comment by domainexpert** [comment]
As the simplification is a many-to-one mapping of constraints, maintaining the inverse mapping will allow us to recover the unsatisfiability core in the original constraints before simplification from the unsatisfiability core after simplification.

**Comment by domainexpert** [comment]
Today's results on https://github.com/tracer-x/klee-examples/blob/master/basic/loop_safe2.c are 0.32s for Tracer-X KLEE and 0.21s for KLEE with STP.

**Comment by domainexpert** [comment]
We attempt to resolve this in #268 using slightly different approach, that is, via copying `simplifyExpr` into a version that can return the unsat core.

**Comment by domainexpert** [comment]
The different approach mentioned previously was actually just the same approach. This issue is resolved via #268.
