### ISSUE TITLE
WP: Instructions not marked correctly in reverse traversal

### ISSUE THREAD

**Issue by rasoolmaghareh** [tracer-x/klee#290]
In the function WeakestPreCondition::markVariables it is observed that sometimes the order of instructions is incorrect. As a result the marking of the instructions is performed incorrectly.

**Comment by domainexpert** [comment]
@rasoolmaghareh Similar to #291, this issue is specific to a WIP PR (#283). I would instead add this as a comment to the WIP PR, so that we keep the issue board for discussion about the `master` branch only.

**Comment by rasoolmaghareh** [comment]
I will close this issue and add it as a comment to PR #283.
