### ISSUE TITLE
Fourier-Motzkin for Quantifier Elimination

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#33]
Subsumption checks involve quantified formulas. In case the formulas involve linear arithmetic constraints, we make an assumption that the variables are in real number domain and use Fourier-Motzkin elimination to remove quantification. As I see it, there are three possible approaches:
1. Look into Z3 quantifier elimination for real linear arithmetic. Importantly, we need a simplification API to eliminate existentially-quantified variables. If such exists, the best is just to use it, as Z3 is already integrated.
2. Interface with CLP(R). The disadvantages are:
    a. the interfacing work will take time, and
    b. this makes the code harder to maintain, as it will include another third-party.
3. Write our own. Fourier-Motzkin is not hard to write, and it would probably only take the same amount of time as interfacing with CLP(R).

**Comment by domainexpert** [comment]
Another option is:
4. Use FM library from http://web.cse.ohio-state.edu/~pouchet/software/fm/ the advantage over CLP(R) is that this may already have well-defined API, but this issue has to be investigated first.
Thanks to @feliciahalim for the info.

**Comment by domainexpert** [comment]
@feliciahalim I have added the method `simplifyWithFourierMotzkin` in `SubsumptionTableEntry` class, where I think the Fourier-Motzkin procedure should be located in. The location is such that logic is that we invoke Fourier-Motzkin only when the existing simplification fails. Right now the method simply returns its own argument, but you can change this to implement Fourier-Motzkin elimination.

**Comment by feliciahalim** [comment]
@domainexpert Thanks Andrew.

**Comment by domainexpert** [comment]
@feliciahalim It should be in commit https://github.com/feliciahalim/klee/commit/97ae7495b14b88f16cb69175bbeca9e93c613e3a. Sorry for the earlier problem.

**Comment by domainexpert** [comment]
PR #43 is on an implementation of Fourier-Motzkin elimination. Discussion continues there.
