### ISSUE TITLE
Missing markings by WP subsumption leads to incorrect WP of parent node

### ISSUE THREAD

**Issue by xuanlinhha** [tracer-x/klee#344]
![img_2704](https://user-images.githubusercontent.com/7811929/47405215-1357aa00-d783-11e8-96b6-ba174a51d4cd.jpg)

Right subtree is subsumed by WP of the LHS but a[4] is yet to be marked by visiting RHS.
Therefore, merging WP is incorrect.

**Comment by rasoolmaghareh** [comment]
fixed via reimplementation.
