### ISSUE TITLE
Making global vars interpolation check as an option

### ISSUE THREAD

**Issue by rasoolmaghareh** [tracer-x/klee#369]
@xuanlinhha: I wanted to ask to add the global vars interpolation check as an option.
@sanghu1790 has reported that he has had some performance issues on some of the programs. I also have noticed that the performance drops in some WP programs.

**Comment by xuanlinhha** [comment]
we add this option is on which branch @rasoolmaghareh ?

**Comment by xuanlinhha** [comment]
Hi, 
I added one option `mark-global` to branch `global-mark` to enable/disable marking global variables.

**Comment by rasoolmaghareh** [comment]
Fixed in #370
