### ISSUE TITLE
Tracer-X has issue on system call

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#53]
@domainexpert 
specifically happened when executed for Minix tr: https://github.com/feliciahalim/klee-examples/commit/e5e1d751b33d1fd0faf67fa0089a7d48383874b2

notes: current makefile is not suitable to run minix tr since it uses additional arguments. In order to run it, please run using the configuration in the comment section. I am still learning to modify the makefile to adapt with this case.

**Comment by feliciahalim** [comment]
@domainexpert I just execute tr.c where it contains system calls and Tracer-X (master branch) executed it with no problem. This is the arguments that I have used to execute tr.c. 
--max-time=120 -libc=uclibc --posix-runtime -only-output-states-covering-new -allow-external-sym-calls ./tr.bc --sym-arg 1 --sym-arg 1 --sym-arg 1 --sym-files 2 2000 --max-fail 1 
It shows Tracer-X able to execute program with system call, but probably needs more testing that it also works for various setting of arguments.

**Comment by domainexpert** [comment]
@feliciahalim Thanks! Would you please do more runs, at least varying the argument sizes, like you did previously: 2 arguments 2 characters long and 3 arguments, each 1 character long. If they are fine, I will be happy for trfix3 to be merged to master, but even if that's the case I think we should not close this issue yet until we could run all of coreutils programs without modifications.

**Comment by feliciahalim** [comment]
@domainexpert I have runs some more experiments. Please see the report [here](https://docs.google.com/document/d/1Q2glDBcAsSINWgxIVCXCzucmZtvs1LoVeM5R6o2Z11Y/edit?usp=sharing) on page 2. If you are happy with the result, please merged it to master. Thanks
