### ISSUE TITLE
Project Subtitle Needs Updating

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#56]
Project subtitle of feliciahalim/klee is currently the same as KLEE. In order to be more informative, I suggest changing it to "KLEE Symbolic Virtual Machine with Tracer-X Extension" with website http://paella.ddns.comp.nus.edu.sg/tracerx/.

**Comment by feliciahalim** [comment]
Please see this PR: https://github.com/feliciahalim/klee/pull/61
