### ISSUE TITLE
Code Formatting Issues

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee#9]
Let's follow LLVM coding standard http://llvm.org/docs/CodingStandards.html
In particular,
1. /// should be used only for doxygen-style comments and // for explanations within code.
2. Names should be in camel casing, e.g., **unsatCore** instead of **unsat_core**. (Strictly speaking, the coding standard requires **UnsatCore**, but let's follow KLEE convention instead.)
3. Do not use **using namespace std**. Instead, prefix std components with **std::**. As we are implementing code for klee namespace, we should not use **using namespace llvm** as well.
4. Use preincrement whenever possible.
5. Don't evaluate **end()** everytime through a loop.

**Comment by feliciahalim** [comment]
2: unsat_core is changed into unsatCore
other issue can be discussed later

**Comment by feliciahalim** [comment]
For point no 4, I think it is okay to use both postincrement and preincrement since the original KLEE also do in both ways.

**Comment by domainexpert** [comment]
@feliciahalim The issue here is not just syntactic, but also that of performance. Postincrement may require temporary storage of the computed value, in which case it is less efficient than preincrement, which usually simply increments the value and returns the result. This issue is mentioned somewhere in http://llvm.org/docs/CodingStandards.html.

**Comment by feliciahalim** [comment]
@domainexpert Okay thank you for the explanation, it is a good reference. I will make sure to use preincrement in the future.

**Comment by domainexpert** [comment]
Fixed in #102.
