### ISSUE TITLE
Analysis of successful subsumption check in coreutils

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#94]
There's a need to further analyze the successful subsumption check in coreutils. I am thinking to let tracer-x produce separate file that list the successful subsumption check that contains the program location (if possible), current constraint, and interpolant query. 

Please let me know if there's any other ideas.

**Comment by domainexpert** [comment]
@feliciahalim For short runs, these information are provided in the tree generated using Tracer-X `-output-tree` option.

**Comment by domainexpert** [comment]
@feliciahalim It seems there has been no problem raised by research group members regarding the use of the tree generated with `-output-tree`, hence I close this issue.
